# Add application configuration variables here, as shown below.
#
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
FACEBOOK_KEY: 523571137723133
FACEBOOK_SECRET:  58b5cbbd891703e39b2ef7e45a170dca
CONSUMER_KEY: NxOIW1bw4QwuhZUEkBCw
CONSUMER_SECRET: kHGQSjZxLIKsU68Ceu3VCJD6qOrCQX3XbNBIgbM7Q
MONGOHQ_URL:  mongodb://heroku_app18494305:u8d0qba5h03l17a33ilev74ud9@ds049198.mongolab.com:49198/heroku_app18494305
MANDRILL_USERNAME: marcobrien12@gmail.com
MANDRILL_APIKEY: 866355d0-9b9d-4680-883d-ffc839cb46e2